---
x_path: processed_data_path
y_path: score_to_predict_path
out_path: /ix/djishnu/Akanksha/SLIDE_git/runs/ERCC1_KO_MF
delta:
  - 0.01
lambda:
  - 0.5
spec: 0.3
y_factor: false
thresh_fdr: 0.2
y_levels: NULL
eval_type: corr
SLIDE_iter: 500
SLIDE_top_feats: 10
CViter: 10
do_interacts: TRUE




